app/models.py
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app import db
from . import login_manager


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), nullable=False, unique=True)
    email = db.Column(db.String(255), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False,  unique=True)
    comment = db.relationship('Comment', backref='username', lazy='dynamic')

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    def set_password(self, password):
        pass_hash = generate_password_hash(password)
        self.password = pass_hash

    def verify_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return f'User: {self.username}'



class Blog(db.Model):
    __tablename__ = 'blogs'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), nullable=False)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('blogs.id'), nullable=False)

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    def delete_blog(self):
        db.session.delete(self)
        db.session.commit()

    @classmethod
    def get_user_blogs(cls,id):
        blogs = Blog.query.filter_by(user_id = id).order_by(Blog.date_posted .desc()).all()
        return blogs

    @classmethod
    def get_all_blogs(cls):
        return Blog.query.order_by(Blog.date_posted ).all()

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"


class Comment(db.Model):
    __tablename__ = "comments"

    id = db.Column(db.Integer, primary_key = True)
    comment = db.Column(db.String)
    comment_at = db.Column(db.DateTime)
    comment_by = db.Column(db.String)
    like_count = db.Column(db.Integer, default = 0)
    blog_id = db.Column(db.Integer, db.ForeignKey("blogs.id"))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def delete_comment(cls, id):
        gone = Comment.query.filter_by(id = id).first()
        db.session.delete(gone)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(blog_id = id).all()
        return comments        


    @property
    def password(self):
        raise AttributeError("You cannot read the password attribute")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # User like logic
    def like_post(self, post):
        if not self.has_liked_post(post):
            like = BlogLike(user_id = self.id,blog_id = post.id)
            db.session.add(like)

    # User dislike logic
    def unlike_post(self, post):
        if self.has_liked_post(post):
            BlogLike.query.filter_by(
                user_id = self.id,
                blog_id = post.id).delete()

    # Check if user has liked post
    def has_liked_post(self, post):
        return BlogLike.query.filter(
            BlogLike.user_id == self.id,
            BlogLike.blog_id == post.id).count() > 0

    # string representaion to print out a row of a column, important in debugging
    def __repr__(self):
        return f"User {self.username}"


class Subscribers(db.Model):
    __tablename__ = "subscribers"
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(255), unique = True, index = True)

class BlogLike(db.Model):
    __tablename__ = "blog_like"
    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    blog_id = db.Column(db.Integer, db.ForeignKey("blogs.id"))


class Quote:
    """
    Blueprint class for quotes consumed from API
    """
    def __init__(self, author, quote):
        self.author = author
        self.quote = quote

    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, TextAreaField, SubmitField
from wtforms.validators import InputRequired

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap


app=Flask(__name__)
bootstrap = Bootstrap(app)

def create_app(config_name):
    app.config.from_object(config_options[config_name])



    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main=Blueprint('main', __name__)
from . import views, errors

app/main/views.py
from flask import (render_template, request, redirect, url_for, abort, flash)
from . import main
from ..models import Blog, User, Comment, Subscribers
from flask_login import login_required, current_user
from .forms import (UpdateProfile, BlogForm, CommentForm, UpdateBlogForm)
from datetime import datetime
from .. import db
from ..requests import get_quote
from ..email import welcome_message, notification_message

@main.route('/')
def index():
    blogs = Blog.get_all_blogs()
    quote = get_quote()

    if request.method == "POST":
        new_sub = Subscribers(email = request.form.get("subscriber"))
        db.session.add(new_sub)
        db.session.commit()
        welcome_message("Thank you for subscribing to the Hands On", "email/welcome", new_sub.email)
    return render_template('index.html', quote = quote, blog = blogs)

# about
@main.route('/about')
def about():
    return render_template('about.html')

# blog posts
@main.route("/blog/<int:id>", methods = ["POST", "GET"])
def blog(id):
    blog = Blog.query.filter_by(id = id).first()
    comments = Comment.query.filter_by(blog_id = id).all()
    comment_form = CommentForm()
    comment_count = len(comments)

    if comment_form.validate_on_submit():
        comment = comment_form.comment.data
        comment_form.comment.data = ""
        comment_alias = comment_form.alias.data
        comment_form.alias.data = ""
        if current_user.is_authenticated:
            comment_alias = current_user.username
        new_comment = Comment(comment = comment, 
                            comment_at = datetime.now(),
                            comment_by = comment_alias,
                            blog_id = id)
        new_comment.save_comment()
        return redirect(url_for("main.blog", id = blog.id))

# delete comment
@main.route("/blog/<int:id>/<int:comment_id>/delete")
def delete_comment(id, comment_id):
    blog = Blog.query.filter_by(id = id).first()
    comment = Comment.query.filter_by(id = comment_id).first()
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for("main.blog", id = blog.id))

#  new blog post
@main.route('/newblog', methods=['POST', 'GET'])
@login_required
def new_blog():
    blog_form= BlogForm()
    if blog_form.validate_on_submit():
        flash('Your post has been created', 'success')
        blog_title = blog_form.title.data
        blog_form.title.data = ""
        blog_content = blog_form.content.data 
        blog_form.content.data = ""
        new_blog = Blog(blog_title = blog_title,
                        blog_content = blog_content,
                        posted_at = datetime.now(),
                        blog_by = current_user.username,
                        user_id = current_user.id)
        new_blog.save_blog()
        db.session.add(new_blog)
        db.session.commit()
        subs = Subscribers.query_all()
        for sub in subs:
            notification_message(blog_title, "email/notification", sub.email, new_blog = new_blog)
            pass
        return redirect(url_for("main.blog", id = new_blog.id))
    
    return render_template('newblog.html', title='New Blog', blog_form=blog_form)

# edit or update blog post
@main.route("/blog/<int:id>/update", methods = ["POST", "GET"])
@login_required
def edit_post(id):
    blog = Blog.query.filter_by(id = id).first()
    edit_form = UpdateBlogForm()

    if edit_form.validate_on_submit():
        blog.blog_title = edit_form.title.data
        edit_form.title.data = ""
        blog.blog_content = edit_form.content.data
        edit_form.content.data = ""

        db.session.add(blog)
        db.session.commit()
        return redirect(url_for("main.blog", id = blog.id))

    return render_template("editblogpost.html", blog = blog, edit_form = edit_form)

   

app/templates/base.html
{% import 'bootstrap/wtf.html' as wtf %}

<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block styles%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Special+Elite&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/6.1.1.0/css/font-awesome.min.css">
    {% endblock %}
    <title>HANDS ON</title>
</head>

<body>
    {% block navbar%}
    {% include 'navbar.html'%}
    {% endblock %}
 
    {% block content%}
    {% endblock %}

    {% block footer %}
    {% include 'footer.html'%}
    {% endblock %}

    {% block scripts%}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='JS/script.js') }}"></script>
    {% endblock %}
</body>

</html>

app/templates/footer.html
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://twitter.com/arinahgladoo" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.linkedin.com/in/gladys-wahito-wambura/" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/gladyswambura" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <img src="{{ url_for('static', filename='images/bloglogo.png') }}" alt="logo" width='100'
                    height="100" alt="">
                <p class="copyright text-muted">Copyright &copy; Gladys 2020</p>
            </div>
        </div>
    </div>
</footer>

app/templates/index.html
{% extends 'base.html'%}

{% block content%}
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<main class="container">
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">Welcome to Hands On.</h1>
        <span class="subheading"><i class="fas fa-quote-left"></i> <em>{{quote.quote}}</em> <i
                 class="fas fa-quote-right"></i></span><br>
        <h2 class="lead my-3">{{quote.author}}</h2><br><br>
        <p class="lead mb-0"><a href="#" class="text-white fw-bold">{{quote.permalink}}</a></p>
    </div>
</div>

<div class="row">
<div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <i class="fa-solid fa-pen"></i>
            <strong class="d-inline-block mb-2 text-success">{{ blog.title }}</strong>
            <h3 class="mb-0">{{ blog.username }}</h3>
            <small class="text-muted">{{ blog.date_posted }}</small>
            <p class="mb-auto article-content">{{ blog.content }}</p>
            <a href="#" class="stretched-link">{{blog.username}}</a>
        </div>
        <div class="col-auto d-none d-lg-block">
            <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img"
                aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef"
                    dy=".3em">New Blog</text>
            </svg>
        </div>
    </div>
</div>
<div class="col-md-2"></div>
    <!-- sticky note -->
    <div class="col-md-4">
        <div class="position-sticky" style="top: 2rem;">
            <div class="p-4 mb-3 bg-light rounded">
                <h4 class="fst-italic">About</h4>
                <p class="mb-0">Hands on, is a blog site developed in may 2022, by Gladys Wambura.
                    We are here to make you feel at place and enjoy every bit of this articles.
                </p>
            </div>
        </div>

        <div class="p-4">
            <h4 class="fst-italic">Find me on:</h4>
            <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a href="https://github.com/gladyswambura">GitHub</a>
                </li>
                <li class="list-group-item list-group-item-light">
                    <a href="https://www.linkedin.com/in/gladys-wahito-wambura/">Linkedin</a>
                </li>
            </ul>
        </div>
    </div>
</div>
</main>
{%endblock%}

app/templates/navbar.html
<nav class="navbar navbar-expand-md bg-light" aria-label="navbar" style="background-color: rgb(199, 154, 161)">
    <div class="container">
        <a class="navbar-brand" href="#"><img src="{{ url_for('static', filename='images/bloglogo.png') }}"alt="logo"width='100' height="100"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
            aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbars">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/index.html">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/index.html">Home</a>
                </li>
                <!-- right -->
                <div class="navbar-nav ms-auto mb-2 mb-md-0">
                {% if current_user.is_authenticated%}
                    <a class="nav-item nav-link" href="/newblog">New Post</a>
                    <a class="nav-item nav-link" href="/account">Account</a>
                    <a class="nav-item nav-link" href="/login">Login</a>
                {% else %}
                    <button class="btn btn-outline-primary"><a class=" nav-item nav-link" href="/signup">SignUp</a>SignUp</button>
                    <a class="nav-link nav-item" href="/logout">Logout</a>
                {% endif %}
                </div>
            </ul>
        </div>
    </div>
</nav>

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block content %}
<div class="container content">
    <div class="row profile">
        <div class="col-md-3">
            <div class="profile-sidebar position-fixed">
                <!-- SIDEBAR USERPIC -->
                {%if user.username == 'catherine244'%}
                <div class="profile-userpic">
                    <img src="https://avatars1.githubusercontent.com/u/56637877?s=400&v=4" class="img-responsive" alt=""
                        height="250" width="250">
                </div>
                {%else%}
                <div class="profile-userpic">
                    <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img-responsive" alt="" height="250"
                        width="250">
                </div>
                {%endif%}
                <!-- SIDEBAR USER TITLE -->
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name">
                        <strong>{{user.first_name}} {{user.last_name}}</strong>
                    </div>
                    <div class="profile-usertitle-job">
                        <small>{{user.username}}</small>
                    </div>
                    {%if user.bio%}
                    <p>{{user.bio}}</p>
                    {%else%}
                    <p>No bio</p>
                    {%endif%}
                </div>
                <!-- END SIDEBAR USER TITLE -->
                <!-- SIDEBAR MENU -->
                {%if current_user.is_authenticated%}
                <hr>
                <div class="profile-usermenu sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('main.update_profile', id = user.id)}}">
                                <i class="fas fa-user-edit"></i>
                                Account Settings </a>
                        </li>
                    </ul>
                </div>
                {%endif%}
                <!-- END MENU -->
            </div>
        </div>
        <div class="col-md-9">
            <div class="profile-content">
                {%for post in posts[::-1]%}
                <div class="post-preview">
                    {%if current_user.is_authenticated%}
                    <div style="float: right; padding-bottom: 50px">
                        <a href="{{url_for('main.edit_post', id = blog.id)}}" class="btn btn-outline-info btn-sm"><i
                                class="far fa-edit"></i></a>
                        <a href="{{url_for('main.delete_blog', id = user.id, blog_id = blog.id)}}"
                            class="btn btn-outline-danger btn-sm"><i class="far fa-trash-alt"></i></a>
                    </div>
                    {%endif%}
                    <a href="{{url_for('main.blog', id = blog.id)}}">
                        <h2 class="blog-title">
                            {{blog.blog_title}}
                        </h2>
                        <h3 class="blog-subtitle">
                            {{blog.blog_content | truncate(45) | safe}}
                        </h3>
                    </a>
                    <div class="blog-meta">posted by
                        <a href="/profile/{{blog.user_id}}">{{blog.blog_by}}</a>
                        on {{blog.posted_at.strftime('%B %d, %Y')}}
                    </div>
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
</div>

{%endblock%}